blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/airml/airml/discussions/new?category=q-a
    about: Ask questions in GitHub Discussions
  - name: Documentation
    url: https://github.com/airml/airml#readme
    about: Read the documentation
